# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: true

    App\Payment\Infrastructure\Persistence\Repository\DoctrineEmployeeRepository: ~
    App\Payment\Infrastructure\Persistence\Repository\DoctrineDepartmentRepository: ~
    App\Payment\Infrastructure\Persistence\Repository\DoctrineDepartmentBonusRuleRepository: ~
    App\Payment\Infrastructure\Persistence\Repository\DoctrineRemunerationReportRepository: ~

    App\Payment\Infrastructure\Persistence\Query\DoctrineRemunerationReportQuery: ~

    App\Payment\Application\UseCase\RemunerationReport\Generate\GenerateSalaryReportUseCasePort: ~

    App\Payment\Application\Query\RemunerationReports\RemunerationReportQueryInterface: ~

    App\Payment\Application\UseCase\RemunerationReport\Delete\DeleteAllReportsUseCasePort: ~